[package]
name = "macmahon-web"
version = "0.1.0"
edition = "2021"

[dependencies]
macmahon-common = { path = "../macmahon-common", features = ["wasm"]}
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
